################################
# API Manager
autodiscoveryId: "000000"

# Listener
https:
  port: "8090"

protocol: "HTTPS"
################################

system-name:
  password: "${secure::system-name.password}"